# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  Build.Configuration: 'Release'

steps:
- script: dotnet build -c $(Build.Configuration)
  displayName: 'Build solution'

- script: dotnet test
  displayName: 'Run unit tests'

- task: CopyFiles@2
  displayName: 'Stage build artifacts'
  inputs:
    contents: '**/bin/$(Build.Configuration)/*.nupkg'
    targetFolder: $(Build.ArtifactStagingDirectory)
    cleanTargetFolder: true
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'nuget-packages'